export const mockProducts = [
  {
    id: 1,
    name: "Wireless Headphones",
    description:
      "Premium wireless headphones with high-quality sound, noise cancellation, and long battery life. Perfect for music lovers and professionals who need clear audio for calls and meetings.",
    price: "129.99",
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e",
    category: "Electronics",
    featured: true,
    isNew: false,
    onSale: false,
    rating: "4.5",
    reviewCount: 42,
    originalPrice: null,
  },
  {
    id: 2,
    name: "Smart Watch",
    description:
      "Health & fitness tracker with heart rate monitoring, sleep tracking, and smartphone notifications. Water-resistant and long battery life.",
    price: "199.99",
    imageUrl: "https://images.unsplash.com/photo-1546868871-7041f2a55e12",
    category: "Electronics",
    featured: true,
    isNew: false,
    onSale: false,
    rating: "4.0",
    reviewCount: 38,
    originalPrice: null,
  },
  {
    id: 3,
    name: "Running Shoes",
    description:
      "Lightweight & comfortable running shoes with responsive cushioning and breathable mesh upper for maximum comfort and performance.",
    price: "89.99",
    imageUrl: "https://images.unsplash.com/photo-1491553895911-0055eca6402d",
    category: "Fashion",
    featured: true,
    isNew: true,
    onSale: false,
    rating: "5.0",
    reviewCount: 56,
    originalPrice: null,
  },
  {
    id: 4,
    name: "Crossbody Bag",
    description:
      "Stylish & functional crossbody bag with multiple compartments and adjustable strap. Perfect for everyday use.",
    price: "49.99",
    imageUrl: "https://images.unsplash.com/photo-1560343090-f0409e92791a",
    category: "Accessories",
    featured: true,
    isNew: false,
    onSale: true,
    rating: "3.5",
    reviewCount: 24,
    originalPrice: "69.99",
  },
  {
    id: 5,
    name: "Red Sneakers",
    description:
      "Casual & comfortable sneakers with a stylish red design. Made with high-quality materials for durability.",
    price: "79.99",
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
    category: "Fashion",
    featured: false,
    isNew: false,
    onSale: false,
    rating: "4.0",
    reviewCount: 18,
    originalPrice: null,
  },
  {
    id: 6,
    name: "Polaroid Camera",
    description:
      "Instant photography camera that prints physical photos on the spot. Capture memories in a vintage style.",
    price: "149.99",
    imageUrl: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f",
    category: "Electronics",
    featured: false,
    isNew: false,
    onSale: false,
    rating: "4.5",
    reviewCount: 32,
    originalPrice: null,
  },
];
